dbt_project:
  outputs:
    dev:
      job_execution_timeout_seconds: 300
      job_retries: 1
      threads: 1
      type: teradata
      host: daniel-test-september-wteuh1djm0q9u4x5.env.clearscape.teradata.com # Update this field with your teradata instance hostname
      schema: airbyte_td
      tmode: ANSI
      logmech: TD2
      user: demo_user # Update this field with your teradata instance database name
      password: danielTest#01 # Update this field with your teradata instance password
  target: dev

  
